# Generated by Django 5.1.1 on 2024-10-31 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='category_images/')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('status', models.BooleanField(blank=True, default=True, null=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='category.category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
    ]
